### ISSUE TITLE
Check if Github access scope has been revoked by user

### ISSUE THREAD

**Issue by hardiksurana** [ITI/searcch-backend#24]
**Describe the bug**
During registration on the hub through Github, users allow a specific scope of access to their data. But, there is no check performed in the case that access was changed/revoked leading to failures during subsequent logins.

**Expected behavior**
With each login, first confirm if the required accesses have been granted by that user. If not, return an error message. Else, proceed with login.

**Additional context**
None.

**Comment by carboxylman** [comment]
Cleaning up old things... I can't reproduce this.  When I deauthorize our oauth app in my github profile after login, and login again, I am prompted to reauthorize.
