### ISSUE TITLE
Grant admin privs via UI

### ISSUE THREAD

**Issue by carboxylman** [ITI/searcch-backend#59]
What I envision here is that the `Can Admin` column in the frontend admin users page would be made into a toggleable field to change admin status.  Toggling would probably result in an "are you sure" modal.  I really dislike such modals generally, but this is a rarely-used toggle that warrants caution.  Then, we need support in the backend; we have a choice of extending admin privs into `PUT /users/<id>` with content `{ "can_admin": true/false }`, only settable by admins; or we can at this point fork off a separate set of `/admin/x` endpoints for clarity/safety.

**Comment by fallen-axe-shay** [comment]
Raised a PR at https://github.com/ITI/searcch-backend/pull/87.

**Comment by fallen-axe-shay** [comment]
PR has been merged!
