### ISSUE TITLE
add action history, statistics

### ISSUE THREAD

**Issue by carboxylman** [ITI/searcch-backend#65]
We need to track actions and collect statistics:

  * Artifact views per artifact (not including user; just a counter)
  * Artifact views per user (not including artifact; just a counter)
  * Searches (saving keywords or other filters)

We already track artifact edits, new artifacts, ratings, reviews, etc.

**Comment by jelenamirkovic** [comment]
* artifact views - add column to artifact in admin menu
* per user - add two columns in admin menu for artifact views and artifacts owned
* searches - add menu button on the left in the admin menu to show time, user and search term they used

**Comment by fallen-axe-shay** [comment]
PR has been merged!
