### ISSUE TITLE
Automatic ownership invitations

### ISSUE THREAD

**Issue by carboxylman** [ITI/searcch-backend#95]
We want to automatically send invitations for authors with email addresses associated with auto- or admin-imported artifacts.  This requires
* new tables to track the requests
* migrations for the new tables
* a background task (fired by apscheduler) to send any required email and update the db
* new API endpoints to allow admins to monitor issued invitations and to block further invitations upon request (by admin, or by user request)

**Comment by carboxylman** [comment]
This is being done in response to https://github.com/ITI/searcch-issues/issues/46 .

**Comment by brian-blonski** [comment]
Some additional requirements I've captured.

1. If an email address opts out of notifications, they should never get any more notifications at that email.
2. If new artifact is found with an email for an existing user, they should receive ownership invitations to that artifact with number of attempts tracked separately for each artifact.
3. If an email is associated with multiple artifacts, one email should be sent for all of them.

**Comment by brian-blonski** [comment]
Should opting out be a manual admin process? I imagined sending some sort of unique opt-out/unsubscribe link the user could click to send a message to automatically unsubscribe. But we could also just have users reply to the email with unsubscribe and have someone manually make the change.

**Comment by brian-blonski** [comment]
Second pass at the schema.

![image](https://user-images.githubusercontent.com/125314881/223527086-565c6be9-879a-49b5-a516-48908e1c508a.png)

- I'm adding an opt_out field to the Persons Table.
- The Email_Signup_Notification Table joins the Persons and Artifact_Group Tables. On a scheduled job, it populates based on the unowned artifacts. The scheduled job then sends emails based on the attempts and last_attempt field.
- The Email_Signup_Notification_Keys Table may not be necessary. I'm still unsure what the proccess for taking ownership should look like. My assumption here was we could create a secure random key to include in the email that the user could then use to automatically take control of the appropriate artifacts.

**Comment by brian-blonski** [comment]
I have completed most of the database work for this. I have the required tables and a task that builds a list of all the emails with associated names and artifacts to send invitations to, including custom sign-up links.

I need the following to proceed.

- Template for the email, or at least some guidance on what it should say.
- Preferred base url for the sign-up link. I'd suggest something like user/join or user/invitation.
- Confirmation that artifact_groups with user_id==1 are the unowned artifacts. User_id 1 appears to the be ID of the importer. Is this always true?

**Comment by lauratinnel** [comment]
>    Template for the email, or at least some guidance on what it should say.
>    Preferred base url for the sign-up link. I'd suggest something like user/join or user/invitation.
I will work on these two today

>    Confirmation that artifact_groups with user_id==1 are the unowned artifacts. User_id 1 appears to the be ID of the importer. Is this always true?
@carboxylman Can you answer this?

**Comment by lauratinnel** [comment]
I have a draft that is in review by the PIs on the project. Also need a subject line. I am thinking that we want two different emails. One for the initial notice, and a different one for reminder notices.

**Comment by brian-blonski** [comment]
@carboxylman Something else I could use help with is how to create a User acount associated with the Person when they click the sign-up link.

**Comment by brian-blonski** [comment]
@lauratinnel How do you imagine sign up to work? Should it be a special proccess that associates the given documents to their user account, or should we direct them to the normal sign up procedure?

Still waiting on those email templates.

**Comment by brian-blonski** [comment]
@lauratinnel I'm starting to reach the limit of what I can accomplish without the email templates. Can you send over the current drafts so I can start work on turing them into templates and testing email generation?

**Comment by carboxylman** [comment]
Finished in https://github.com/ITI/searcch-backend/commit/f5e06e35c163fb080b78e9d09bf0c694f63c598d .
